# Contains values that affect multiple components of the chart.
global:
  # The main enabled/disabled setting.
  # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
  enabled: false
  # The prefix used for all resources created in the Helm chart.
  name: consul
  # The name of the datacenter that the agents should register as.
  datacenter: dc1
  # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
  tls:
    enabled: false
    httpsOnly: false
    verify: false
  # Enables ACLs across the cluster to secure access to data and APIs.
  acls:
    # If true, automatically manage ACL tokens and policies for all Consul components.
    manageSystemACLs: false
  imageK8S: thanhnguyenvungle/consul-k8s-ha
# Configures values that configure the Consul server cluster.
server:
  enabled: true
  # The number of server agents to run. This determines the fault tolerance of the cluster.
  replicas: 1

syncCatalog:
  enabled: true
  toK8S: false
  # syncClusterIPServices: false
  # nodePortSyncType: "InternalOnly"
  # Only sync explicitly annotated services
  # https://developer.hashicorp.com/consul/docs/k8s/service-sync#enable-and-disable-sync
  default: true
  k8sAllowNamespaces: ["*"]

# Contains values that configure the Consul UI.
ui:
  enabled: true
  # Registers a Kubernetes Service for the Consul UI as a NodePort.
  service:
    type: NodePort
# Configures and installs the automatic Consul Connect sidecar injector.
connectInject:
  enabled: false

